### ISSUE TITLE
App plays BGM when a car starts.

### ISSUE THREAD

**Issue by hoshikitsunoda** [hoshikitsunoda/driving-game#15]
# Motivation
User can enjoy arcade music while playing the game.
# Implementation

- [x] Find mp3 file of arcade music and put it in the project folder.

- [x] Create embed element and append it to HTML with DOM.

- [x] Add the function to append when the car starts.

- [x] Check if autoplay works.

- [x] Add, commit and push.

**Comment by thebearingedge** [comment]
Be sure you are adding and committing on each task, not just at the end.

**Comment by hoshikitsunoda** [comment]
Ah ok, I didn't know I was supposed to. I'll make sure to commit each task from now!
